language: node_js

node_js:
- "8.9.4"

cache:
  directories:
  - node_modules
  - bower_components

before_script:
- git clone --depth=50 --branch=master https://github.com/dakotaJang/web-component-test-demo.git repo
- cd repo
- npm install -g typescript tslint

script:
- tslint -p .
