language: node_js

node_js:
- "8.9.4"

cache:
  directories:
  - node_modules
  - bower_components

before_script:
- npm install
- npm install -g web-component-tester bower webpack typescript tslint

script:
- tslint -p .
